### ISSUE TITLE
종이(서류), 부대마크 데이터 수집하기

### ISSUE THREAD

**Issue by zheedong** [osamhack2021/AI_APP_WEB_Canary_Canary#4]
크롤링 등의 방법을 이용하고 결과물 공유하기

**Comment by zheedong** [comment]
Due date 2021/09/19

**Comment by wonbeomjang** [comment]
부대 마크 데이터 수집 약 990여개
https://drive.google.com/drive/folders/1wL9k8jBfaHJDeYnnk5vLsynTc8ZpPkwC?usp=sharing

**Comment by zheedong** [comment]
부대 마크 데이터 수집 1076 장
